# Generated by Django 5.2.4 on 2025-07-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagem', models.ImageField(upload_to='postagens/')),
                ('texto', models.TextField()),
                ('data_publicacao', models.DateField()),
            ],
        ),
    ]
